sudo: required
language: cpp
arch:
  packages:
    # aur packages
    - inox
  script:
    - "./build_script.sh"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
